default:
  # NOTE: options that apply to all the whitman data repos
  # are in data/config/private.yml
  # (solr_core, solr_path, solr_variables, etc)

  shortname: whitman-marginalia
  collection_desc: Marginalia for The Walt Whitman Archive
  tei_solr_xsl: collections/whitman-marginalia/scripts/solr_transform_tei.xsl
  # es_type:

  variables_solr:
    figures: false
    fw: false
    pb: false
    project: The_Walt_Whitman_Archive
    slug: whitman-marginalia
development:
  # development overrides here
production:
  # production overrides here
