default:
  collection: whitman-marginalia
  shortname: whitman-marginalia
  site_url: https://whitmanarchive.org
  solr_core: api_whitman
  tei_solr_xsl: scripts/overrides/solr_transform_tei.xsl
  data_base: https://whitmanarchive.org/media
  media_base: https://whitmanarchive.org/media
  tei_html_xsl: scripts/overrides/tei_to_html.xsl
  variables_html:
    image_large: 1200
    image_thumb: 80
  api_version: "2.0"
  es_index: whitman-api_v2
  threads: 1

development:
  es_path: https://set_in_private_config/elastic
  site_url: https://set_in_private_config
  solr_path: https://set_in_private_config/solr
  data_base: https://set_in_private_config/media

  variables_solr:
    project: The_Walt_Whitman_Archive
    site_url: https://set_in_private_config
    slug: whitman-marginalia

production:
  site_url: https://whitmanarchive.org
  solr_path: https://set_in_private_config/solr

  variables_solr:
    project: The_Walt_Whitman_Archive
    site_url: https://whitmanarchive.org
    slug: whitman-marginalia
