default:
  collection: whitman-marginalia
  shortname: whitman-marginalia
  site_url: https://whitmanarchive.org
  solr_core: api_whitman
  tei_solr_xsl: scripts/overrides/solr_transform_tei.xsl
  data_base: https://whitmanarchive.org/media
  media_base: https://whitmanarchive.org/media

development:
  es_path: https://whitman-dev.unl.edu/elastic
  es_index: api_v1
  site_url: https://whitman-dev.unl.edu
  solr_path: https://whitman-dev.unl.edu/solr
  data_base: https://whitman-dev.unl.edu/media

  variables_solr:
    project: The_Walt_Whitman_Archive
    site_url: https://whitman-dev.unl.edu
    slug: whitman-marginalia

production:
  site_url: https://whitmanarchive.org
  solr_path: https://whitman-prod.unl.edu/solr

  variables_solr:
    project: The_Walt_Whitman_Archive
    site_url: https://whitmanarchive.org
    slug: whitman-marginalia
